export enum PAYMENT_ADMIN_KEYS {
  GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS',
  GET_ALL_REFUNDS = 'GET_ALL_REFUNDS',
  GET_PAYMENT_STATS = 'GET_PAYMENT_STATS',
  GET_TRANSACTION_BY_ID = 'GET_TRANSACTION_BY_ID',
  GET_REFUND_BY_ID = 'GET_REFUND_BY_ID',
  REFUND_TRANSACTION = 'REFUND_TRANSACTION',
}
