export enum ROUTES {
  USERS = 'users',
  PACKS = 'packs',
  PLANS = 'plans',
  TRANSACTIONS = 'transactions',
  PAYOUTS = 'payouts',
  DASHBOARD = '/dashboard',
  AGENCIES = 'agencies',
}

export const APP_ROUTES = {
  ROOT: '/',
  _2FA: '/totp',
  SIGN_IN: '/signin',
  PROTECTED: '/not-authenticated',
};

export const BO_ROUTES = {
  DASHBOARD: ROUTES.DASHBOARD,
  AGENCIES: {
    LIST: `${ROUTES.DASHBOARD}/${ROUTES.AGENCIES}`,
    DETAILS: `${ROUTES.DASHBOARD}/${ROUTES.AGENCIES}/details`,
  },
  USERS: {
    LIST: `${ROUTES.DASHBOARD}/${ROUTES.USERS}`,
    DETAILS: `${ROUTES.DASHBOARD}/${ROUTES.USERS}/details`,
  },
  PACKS: {
    LIST: `${ROUTES.DASHBOARD}/${ROUTES.PACKS}`,
    DETAILS: `${ROUTES.DASHBOARD}/${ROUTES.PACKS}/details`,
  },
  PLANS: {
    LIST: `${ROUTES.DASHBOARD}/${ROUTES.PLANS}`,
    DETAILS: `${ROUTES.DASHBOARD}/${ROUTES.PLANS}/details`,
    CREATE: `${ROUTES.DASHBOARD}/${ROUTES.PLANS}/create`,
    UPDATE: `${ROUTES.DASHBOARD}/${ROUTES.PLANS}/update`,
    TOGGLE_STATUS: `${ROUTES.DASHBOARD}/${ROUTES.PLANS}/toggle-status`,
    DELETE: `${ROUTES.DASHBOARD}/${ROUTES.PLANS}/delete`,
  },
  TRANSACTIONS: {
    LIST: `${ROUTES.DASHBOARD}/${ROUTES.TRANSACTIONS}`,
    DETAILS: `${ROUTES.DASHBOARD}/${ROUTES.TRANSACTIONS}/details`,
  },
  PAYOUTS: {
    LIST: `${ROUTES.DASHBOARD}/${ROUTES.PAYOUTS}`,
    DETAILS: `${ROUTES.DASHBOARD}/${ROUTES.PAYOUTS}/details`,
  },
};

export const ROUTE_PARENTS: Record<string, string> = {
  [BO_ROUTES.USERS.DETAILS]: BO_ROUTES.USERS.LIST,
  [BO_ROUTES.AGENCIES.DETAILS]: BO_ROUTES.AGENCIES.LIST,
  [BO_ROUTES.PACKS.DETAILS]: BO_ROUTES.PACKS.LIST,
  [BO_ROUTES.PLANS.DETAILS]: BO_ROUTES.PLANS.LIST,
  [BO_ROUTES.TRANSACTIONS.DETAILS]: BO_ROUTES.TRANSACTIONS.LIST,
  [BO_ROUTES.PAYOUTS.DETAILS]: BO_ROUTES.PAYOUTS.LIST,
};
